import initScrollSuave from './modules/scroll-suave.js';
initScrollSuave();
import initAnimacaoScroll from './modules/animacao-scroll.js';
initAnimacaoScroll();
import initTabNav from './modules/animacao-tab.js';
initTabNav();
import initAccordion from './modules/animacao-accordion.js';
initAccordion();
import initModal from './modules/modal.js';
initModal();
import initToolTip from './modules/tooltip.js';
initToolTip();